name: Build website
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Build-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Adds keys to work with other repositories used in this lesson (e.g., UCL/github-example)
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: actions/cache@v4 # FIXME: add apt(latex)
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '.github/python/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install TeXLive
        uses: DanySK/setup-texlive-action@0.1.1
      - id: setup-python
        name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: python -m pip install -r .github/python/requirements.txt
      - name: Building notes
        run: make ready
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - name: Install apt requirements
        run: gem install bundler
      - name: Install apt requirements
        run: bundle exec jekyll build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site
      - name: Deploy to GitHub Pages
        if: >
          success()
          && github.ref == 'refs/heads/main'
          && github.repository == 'UCL/rsd-engineeringcourse'
        id: deployment
        uses: actions/deploy-pages@v4
